# -*- coding: utf-8 -*-
"""POS analysis with SpaCy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgrSDAi0ZR8_IngOJOc131Entps3tKLV
"""

import spacy

# Load the SpaCy English model
nlp = spacy.load("en_core_web_sm")

# Text to analyze
text = "Locate the corner hole on roof of shipping container. This hole faces upward and is larger than the side holes, which face outward."

# Process the text with SpaCy
doc = nlp(text)

# Initialize counters for each part of speech
pos_counts = {
    "NOUN": 0,
    "VERB": 0,
    "ADJ": 0,
    "ADV": 0,
    "PRON": 0,
    "ADP": 0,
    "CONJ": 0,
    "DET": 0,
    "NUM": 0,
    "PROPN": 0,
    "PUNCT": 0,
    "SYM": 0,
    "X": 0
}

# Create lists to store each type of POS
pos_words = {pos: [] for pos in pos_counts.keys()}

# Iterate through tokens and count parts of speech
for token in doc:
    pos = token.pos_  # Part of speech
    if pos in pos_counts:
        pos_counts[pos] += 1
        pos_words[pos].append(token.text)

# Print results
print("Detailed POS Analysis:")
for pos, count in pos_counts.items():
    if count > 0:  # Only print POS types that exist in the text
        print(f"{pos}: {count} ({', '.join(pos_words[pos])})")

# Print total counts
print("\nSummary:")
print(f"Total nouns: {pos_counts['NOUN']}")
print(f"Total verbs: {pos_counts['VERB']}")
print(f"Total adjectives: {pos_counts['ADJ']}")
print(f"Total adverbs: {pos_counts['ADV']}")